### ISSUE TITLE
Support for generate css with woff and woff2 fonts

### ISSUE THREAD

**Issue by JosefJezek** [battlesnake/gulp-google-webfonts#32] opened 2017-09-08 12:48 UTC
```css
@font-face {
      font-family: 'Roboto';
      font-style: normal;
      font-weight: 400;
      /* Use local copy of font, if the user does not have that font installed (two different names are tried),
         then the downloadable font is used instead. */
      src: local('Roboto'), local('Roboto-Regular'),
           url(Roboto-normal-400.woff2) format('woff2'),
           url(Roboto-normal-400.woff) format('woff');
    }
```

Safari support woff2 http://caniuse.com/#search=woff2

**Comment by battlesnake** [comment] 2017-09-09 15:05
Duplicate of #5 , still awaiting PR after 2 years

**Closed as completed by battlesnake** 2017-09-09 15:05 UTC
