### ISSUE TITLE
gulp-google-webfonts is not working on Windows

### ISSUE THREAD

**Issue by 0xFelix** [battlesnake/gulp-google-webfonts#2] opened 2015-05-26 19:05 UTC
Hi,

I'm using Windows 8.1 and can't get the plugin to work on my machine. Even the minimalist example out of the readme does not work. Gulp does not output any error but the destination of the fonts stays empty after running the task. Testing the exact same code on OSX does work. Any suggestions?

**Comment by battlesnake** [comment] 2015-05-26 20:45
Hi,

I haven't used Windows in over a decade - I'm not sure what to suggest.  Since it works on Mac (and my Linux laptop+servers), the problem is probably due to Windows' lack of POSIX compliance.  I'll have a look into it tomorrow, but I can't promise anything since I can't reproduce it here.

**Comment by battlesnake** [comment] 2015-06-01 11:48
Closing due to lack of useful debugging information

**Closed as completed by battlesnake** 2015-06-01 11:48 UTC
